# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda6cdccf487e2db74722673d4820eb5a11c4bf90752d04a2d500b5ff8dacb36fc493a43b4eda5767150bfd2baa74f39a67d2fcd3fe81e228d8b0d298d1bfd83

test:
  secret_key_base: eb7c2daefb97a6797d658e33f7bc2b23bd686aa48457b0dc8eff70e41e836e5b497508205b4a52ed38e35e8282ece7c08098585af1d2fda6421c89a4b4c03cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
